name: Java Release Build
on:
  workflow_dispatch:
    inputs:
      scope:
        default: minor
        description: Which version number gets incremented (one of major, minor, patch)
        required: true
      stage:
        default: beta
        description: What kind of release is this? (one of beta, rc, final)
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0 # need full history for reckon (tags)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4
      - name: Build & Test
        # https://github.com/burrunan/gradle-cache-action
        uses: burrunan/gradle-cache-action@a54b6ce2cbbba932e5d142129dddef103e6ad143
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Building & Testing the examples project so that we can do everything in 1 build
          build-root-directory: examples
          arguments: :plugin:assemble :plugin:check assemble check --continue --stacktrace
          properties: |
            reckon.scope=${{ github.event.inputs.scope }}
            reckon.stage=${{ github.event.inputs.stage }}
      - name: Publish Release
        if: github.ref == 'refs/heads/main'
        uses: burrunan/gradle-cache-action@a54b6ce2cbbba932e5d142129dddef103e6ad143
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build-root-directory: plugin
          arguments: publishPlugins --continue --stacktrace
          execution-only-caches: true
          properties: |
            reckon.scope=${{ github.event.inputs.scope }}
            reckon.stage=${{ github.event.inputs.stage }}
            gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
            gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: Push git tag
        if: github.ref == 'refs/heads/main'
        uses: burrunan/gradle-cache-action@a54b6ce2cbbba932e5d142129dddef103e6ad143
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build-root-directory: plugin
          arguments: reckonTagPush --continue --stacktrace
          execution-only-caches: true
          properties: |
            reckon.scope=${{ github.event.inputs.scope }}
            reckon.stage=${{ github.event.inputs.stage }}


